-- 1차 기본 스키마
BEGIN;

CREATE TABLE IF NOT EXISTS public.games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "key" TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    message_id BIGINT,
    game_id BIGINT NOT NULL REFERENCES public.games (id),
    creator_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 10,
    status TEXT NOT NULL DEFAULT 'RECRUITING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    CONSTRAINT matches_capacity_check CHECK (capacity = 10),
    CONSTRAINT matches_status_check CHECK (
        status IN ('RECRUITING', 'PLAYING', 'FINISHED', 'CANCELLED')
    )
);

CREATE TABLE IF NOT EXISTS public.match_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES public.matches (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    team TEXT,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT match_participants_team_check CHECK (team IS NULL OR team IN ('A', 'B')),
    CONSTRAINT match_participants_match_user_key UNIQUE (match_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.match_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES public.matches (id) ON DELETE CASCADE,
    winner_team TEXT NOT NULL,
    memo TEXT,
    recorded_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT match_results_winner_team_check CHECK (winner_team IN ('A', 'B')),
    CONSTRAINT match_results_match_key UNIQUE (match_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS matches_one_active_per_channel_idx
    ON public.matches (guild_id, channel_id)
    WHERE ended_at IS NULL;

CREATE INDEX IF NOT EXISTS matches_game_id_idx
    ON public.matches (game_id);

CREATE INDEX IF NOT EXISTS match_participants_match_id_idx
    ON public.match_participants (match_id);

CREATE INDEX IF NOT EXISTS match_results_match_id_idx
    ON public.match_results (match_id);

INSERT INTO public.games ("key", name)
VALUES ('lol', 'League of Legends')
ON CONFLICT ("key") DO UPDATE SET name = EXCLUDED.name;

ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_results ENABLE ROW LEVEL SECURITY;

COMMIT;

-- 2차 준비 확인과 대기열
BEGIN;

ALTER TABLE public.matches
    ADD COLUMN IF NOT EXISTS recruitment_deadline_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS recruitment_reminded_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS ready_deadline_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS cancel_reason TEXT;

ALTER TABLE public.matches
    DROP CONSTRAINT IF EXISTS matches_status_check;

ALTER TABLE public.matches
    ADD CONSTRAINT matches_status_check CHECK (
        status IN ('RECRUITING', 'READY_CHECK', 'PLAYING', 'FINISHED', 'CANCELLED')
    );

ALTER TABLE public.match_participants
    ADD COLUMN IF NOT EXISTS membership TEXT NOT NULL DEFAULT 'PARTICIPANT',
    ADD COLUMN IF NOT EXISTS ready_at TIMESTAMPTZ;

UPDATE public.match_participants
SET membership = 'PARTICIPANT'
WHERE membership IS NULL;

ALTER TABLE public.match_participants
    DROP CONSTRAINT IF EXISTS match_participants_membership_check;

ALTER TABLE public.match_participants
    ADD CONSTRAINT match_participants_membership_check
    CHECK (membership IN ('PARTICIPANT', 'WAITLIST'));

CREATE INDEX IF NOT EXISTS matches_recruitment_due_idx
    ON public.matches (recruitment_deadline_at)
    WHERE ended_at IS NULL AND status = 'RECRUITING';

CREATE INDEX IF NOT EXISTS matches_ready_due_idx
    ON public.matches (ready_deadline_at)
    WHERE ended_at IS NULL AND status = 'READY_CHECK';

CREATE INDEX IF NOT EXISTS match_participants_fifo_idx
    ON public.match_participants (match_id, membership, joined_at, id);

COMMIT;

-- 3A 게임, 시즌, MMR
BEGIN;

ALTER TABLE public.games
    ADD COLUMN team_size INTEGER NOT NULL DEFAULT 5,
    ADD COLUMN capacity INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN default_rating INTEGER NOT NULL DEFAULT 1000,
    ADD COLUMN k_factor INTEGER NOT NULL DEFAULT 32,
    ADD COLUMN rating_enabled BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE public.games
    ADD CONSTRAINT games_team_size_check CHECK (team_size > 0),
    ADD CONSTRAINT games_capacity_check CHECK (
        capacity > 0 AND capacity % 2 = 0 AND capacity = team_size * 2
    ),
    ADD CONSTRAINT games_default_rating_check CHECK (default_rating > 0),
    ADD CONSTRAINT games_k_factor_check CHECK (k_factor > 0);

ALTER TABLE public.matches DROP CONSTRAINT matches_capacity_check;
ALTER TABLE public.matches
    ADD CONSTRAINT matches_capacity_check CHECK (capacity > 0 AND capacity % 2 = 0);

CREATE TABLE public.seasons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL REFERENCES public.games (id),
    name TEXT NOT NULL CHECK (btrim(name) <> ''),
    started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at TIMESTAMPTZ,
    CONSTRAINT seasons_time_check CHECK (ended_at IS NULL OR ended_at >= started_at)
);

CREATE UNIQUE INDEX seasons_one_active_idx
    ON public.seasons (guild_id, game_id)
    WHERE ended_at IS NULL;

CREATE INDEX seasons_scope_idx
    ON public.seasons (guild_id, game_id, started_at DESC, id DESC);

ALTER TABLE public.matches ADD COLUMN season_id BIGINT;

INSERT INTO public.seasons (guild_id, game_id, name, started_at)
SELECT guild_id, game_id, 'Legacy', min(created_at)
FROM public.matches
GROUP BY guild_id, game_id;

UPDATE public.matches AS m
SET season_id = s.id
FROM public.seasons AS s
WHERE s.guild_id = m.guild_id
  AND s.game_id = m.game_id
  AND s.ended_at IS NULL;

ALTER TABLE public.matches
    ADD CONSTRAINT matches_season_id_fkey
        FOREIGN KEY (season_id) REFERENCES public.seasons (id),
    ALTER COLUMN season_id SET NOT NULL;

CREATE INDEX matches_season_id_idx ON public.matches (season_id);

ALTER TABLE public.match_participants ADD COLUMN rating_snapshot INTEGER;

CREATE TABLE public.player_ratings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL REFERENCES public.games (id),
    season_id BIGINT NOT NULL REFERENCES public.seasons (id),
    user_id BIGINT NOT NULL,
    rating INTEGER NOT NULL,
    games_played INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT player_ratings_games_played_check CHECK (games_played >= 0),
    CONSTRAINT player_ratings_scope_user_key
        UNIQUE (guild_id, game_id, season_id, user_id)
);

CREATE INDEX player_ratings_ranking_idx
    ON public.player_ratings
    (guild_id, game_id, season_id, rating DESC, games_played DESC, user_id);

CREATE TABLE public.rating_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES public.matches (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    rating_before INTEGER NOT NULL,
    rating_delta INTEGER NOT NULL,
    rating_after INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT rating_history_balance_check
        CHECK (rating_after = rating_before + rating_delta),
    CONSTRAINT rating_history_match_user_key UNIQUE (match_id, user_id)
);

CREATE INDEX rating_history_user_idx
    ON public.rating_history (user_id, created_at DESC);

ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.player_ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rating_history ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.seasons FROM PUBLIC;
REVOKE ALL ON TABLE public.player_ratings FROM PUBLIC;
REVOKE ALL ON TABLE public.rating_history FROM PUBLIC;
REVOKE ALL ON SEQUENCE public.seasons_id_seq FROM PUBLIC;
REVOKE ALL ON SEQUENCE public.player_ratings_id_seq FROM PUBLIC;
REVOKE ALL ON SEQUENCE public.rating_history_id_seq FROM PUBLIC;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        REVOKE ALL ON TABLE public.seasons FROM anon;
        REVOKE ALL ON TABLE public.player_ratings FROM anon;
        REVOKE ALL ON TABLE public.rating_history FROM anon;
        REVOKE ALL ON SEQUENCE public.seasons_id_seq FROM anon;
        REVOKE ALL ON SEQUENCE public.player_ratings_id_seq FROM anon;
        REVOKE ALL ON SEQUENCE public.rating_history_id_seq FROM anon;
    END IF;
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
        REVOKE ALL ON TABLE public.seasons FROM authenticated;
        REVOKE ALL ON TABLE public.player_ratings FROM authenticated;
        REVOKE ALL ON TABLE public.rating_history FROM authenticated;
        REVOKE ALL ON SEQUENCE public.seasons_id_seq FROM authenticated;
        REVOKE ALL ON SEQUENCE public.player_ratings_id_seq FROM authenticated;
        REVOKE ALL ON SEQUENCE public.rating_history_id_seq FROM authenticated;
    END IF;
END
$$;

COMMIT;

