BEGIN;

CREATE TABLE IF NOT EXISTS public.games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "key" TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    message_id BIGINT,
    game_id BIGINT NOT NULL REFERENCES public.games (id),
    creator_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    capacity INTEGER NOT NULL DEFAULT 10,
    status TEXT NOT NULL DEFAULT 'RECRUITING',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    CONSTRAINT matches_capacity_check CHECK (capacity = 10),
    CONSTRAINT matches_status_check CHECK (
        status IN ('RECRUITING', 'PLAYING', 'FINISHED', 'CANCELLED')
    )
);

CREATE TABLE IF NOT EXISTS public.match_participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES public.matches (id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    team TEXT,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT match_participants_team_check CHECK (team IS NULL OR team IN ('A', 'B')),
    CONSTRAINT match_participants_match_user_key UNIQUE (match_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.match_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id BIGINT NOT NULL REFERENCES public.matches (id) ON DELETE CASCADE,
    winner_team TEXT NOT NULL,
    memo TEXT,
    recorded_by BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT match_results_winner_team_check CHECK (winner_team IN ('A', 'B')),
    CONSTRAINT match_results_match_key UNIQUE (match_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS matches_one_active_per_channel_idx
    ON public.matches (guild_id, channel_id)
    WHERE ended_at IS NULL;

CREATE INDEX IF NOT EXISTS matches_game_id_idx
    ON public.matches (game_id);

CREATE INDEX IF NOT EXISTS match_participants_match_id_idx
    ON public.match_participants (match_id);

CREATE INDEX IF NOT EXISTS match_results_match_id_idx
    ON public.match_results (match_id);

INSERT INTO public.games ("key", name)
VALUES ('lol', 'League of Legends')
ON CONFLICT ("key") DO UPDATE SET name = EXCLUDED.name;

ALTER TABLE public.games ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.match_results ENABLE ROW LEVEL SECURITY;

COMMIT;
